### ISSUE TITLE
It is not working

### ISSUE THREAD

**Issue by dioubernardo** [ParsePlatform/CloudCodeOAuthGitHubTutorial#6]
In row 169 in main.js
user.getSessionToken()

The User, Session and TokenStorage is ok but the functions always is returning "undefined"

**Comment by DevanshiNigam** [comment]
same problem

**Comment by dioubernardo** [comment]
The problem is that getSessionToken function does not work the same way when Revocable Sessions is active.
Not to modify the code is only make "Revocable Sessions" off the code will work.

To work with "Revocable Sessions" on you need to make some modifications to the code. I will submit a merge with the solution.

**Comment by dioubernardo** [comment]
See this fork https://github.com/dioubernardo/CloudCodeOAuthGitHubTutorial

**Comment by DevanshiNigam** [comment]
its still giving the "login with gitHub failed" alert.

**Comment by dioubernardo** [comment]
I deploy to https://bernardosilva.parseapp.com/ and work

**Comment by gfosco** [comment]
Closing this and we'll merge #7 once @dioubernardo signs the CLA.
