### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by DevanshiNigam** [ParsePlatform/CloudCodeOAuthGitHubTutorial#8]
I am new to this technology. please forgive if the issue is silly, but provide a solution.when 'parse new' is executed, i get "X-Parse-REST-API-Key"" while the code says to enter the javascript key. Is it same? everytime i am running the app, i am getting a login with gitHub failed promt.

**Comment by gfosco** [comment]
They aren't the same, you can get all of your keys on the parse.com settings dashboard for your app.
