### ISSUE TITLE
Session token revoked on other devices with password update

### ISSUE THREAD

**Issue by kynetiv** [ParsePlatform/CloudCodeOAuthGitHubTutorial#9]
Note: I'm using the REST API  for my auth implementation as opposed to this example's Cloud Code approach. This may not be an issue in Cloud Code.

I've noticed that with revocable sessions and the workaround of updating a user's password in order to become the user and get the session token, per #7 , my session token is likewise updated which has the effect of invalidating the previous session token that may have been used to log in on other devices.

In the <a href="http://blog.parse.com/announcements/announcing-new-enhanced-sessions/">new enhanced sessions</a> blog post, it mentions unique session objects per device, however it seems when logging in from the REST API (and perhaps Cloud Code as well?) there isn't a way to determine which installation referred the login and will just default to updating whatever token is available.

Any ideas on how to create a unique session and or avoid invalidating the current session token that may span across multiple devices? Perhaps there is a way to specify the installationId that the user session should be associated with and as such specify which session token to invalidate upon updating a user's password.

**Comment by gfosco** [comment]
Is your app new?  Check the settings page to ensure that revocable sessions are enabled.  Additional logins should NOT revoke previous logins (unless your app is not using revocable sessions.)

You can also enable revocable sessions on a per login level with an additional header listed in the docs. X-Parse-Revocable-Session: 1

https://parse.com/docs/rest/guide#sessions

**Comment by kynetiv** [comment]
Thanks. I had revokable sessions enabled, I just missed this setting...

> Revoke existing session tokens when user changes password
